apiVersion: v1
kind: Service
metadata:
  labels:
    app: issuegen
    argocd.argoproj.io/instance: issuegen
  name: issuegen-svc
spec:
  ports:
    - port: 3100
      targetPort: 8088
  selector:
    app: issuegen
  type: ClusterIP
